### ISSUE TITLE
Ios app

### ISSUE THREAD

**Issue by libea18** [EbrahimTahernejad/xray-mobile#1]
hello
i'm looking for a ios developer for make a vpn app like napsternetV/wingsX/shadowrocket ( with xray-core).
i would be happy if you are able to work us.
if you want, send me an email or telegram id

**Comment by EbrahimTahernejad** [comment]
I'm already working on one with multiple cores which will be free on AppStore.
Do you want to implement anything special into it?

**Comment by libea18** [comment]
Maybe it needs more specific things.
Can you give Telegram id? or email address

**Comment by EbrahimTahernejad** [comment]
ebrahimtahernejad [at] gmail [dot] com

send me your telegram ID there
