### ISSUE TITLE
Does this work with ios-Tunnel?

### ISSUE THREAD

**Issue by houmie** [EbrahimTahernejad/xray-mobile#2]
Hello Ebrahim,

Sorry, I just came across your project here.

Does this support the iOS Network Extension too?

I'm looking for open source projects that support Xray on iOS. I only found Mango.

But it seems the author has stopped updating it for 7 weeks, not quite sure what will happen to that project.

The worst part was when I add his dependencies to my own iOS project, it breaks my ios-tunnel for Wireguard.

I can imagine this has something to do with his XrayKit.

Thanks,
Houman

**Comment by EbrahimTahernejad** [comment]
They will update that project.
Yes, it does support network extension, however, you're going to need a Tun2Socks library for it (leaf or hev-socks5-tunnel would work).

I don't think his XrayKit will break your wireguard tunnel, but you can create isolated targets for each tunnel method and determine which one you want to use by providing the extension's bundle id in your NEVPNManager.
