### ISSUE TITLE
How to ping Config ?

### ISSUE THREAD

**Issue by NDDev19** [EbrahimTahernejad/xray-mobile#4]
Hello
I'm trying to use LibXrayPing(_:) to ping an outbound but all I get in response is:
"proxyconnect tcp: dial tcp :0: connect: can\'t assign requested address"

I'm calling LibXrayPing from the container app not the network extension. 
Ping request passed to the ping method:

```
private func makePingRequest(datDir: String,
                                 configPath: String,
                                 timeout: Int,
                                 url: String,
                                 proxy: String) -> String {
        
        var request = [String: Any?]()
        request["DatDir"] = datDir
        request["ConfigPath"] = configPath
        request["Timeout"] = timeout
        request["Url"] = url
        request["Proxy"] = proxy
        
        let stringData = try! JSONSerialization.data(withJSONObject: request)
        return String(data: stringData, encoding: .utf8)!.toBase64()
    }
```

Should I supply any arguments to the 'proxy' parameter ? I'm leaving it empty.

**Comment by NDDev19** [comment]
I get a ping response when I run it on the network extension.

**Comment by EbrahimTahernejad** [comment]
use this:

https://github.com/EbrahimTahernejad/LibXrayApple

which is the compiled version of this:

https://github.com/EbrahimTahernejad/libXray/tree/warp
